##################################################
### Install required packages
- name: Install required packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

##################################################
### Install Docker CE
- name: Add apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present

- name: Add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable
    state: present

- name: Install Docker CE
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
